Add y/n/a questions
This is useful to check what's going on and skip something if I don't want it to
be installed

diff --git a/esetup b/esetup
--- a/esetup
+++ b/esetup
@@ -3,9 +3,29 @@
 grn="\e[32m"
 cyn="\e[36m"
 rst="\e[0m"    # reset
+all=""
 
 announce() {
-    echo -e $grn"configuring $1"$rst
+  echo
+  echo -e $grn"configuring $1"$rst
+}
+
+yna() {
+  while true; do
+    read -n1 -p "$1? (y/n/a) "
+    echo
+    case $REPLY in
+      [aA] )
+        echo -e $red'abort'$rst
+        exit 1;;
+      [yY] )
+        return 0;;
+      [nN] )
+        return 1;;
+      * )
+        echo -e $red'please answer y/n/a'$rst;;
+    esac
+  done
 }
 
 dostep() {
@@ -14,12 +34,24 @@ dostep() {
   cmd=$3
   echo
   echo -e $grn"step $step: $cyn$cmd$rst"
-  echo -e $cyn"running $cmd$rst"
-  echo
-  if [[ $sdo == "y" ]] ; then
-    sudo $cmd
+  if [[ $all == "" ]] ; then
+    if yna "run $cmd"; then
+      echo -e $cyn"running $cmd$rst"
+      echo
+      if [[ $sdo == "y" ]] ; then
+        sudo $cmd
+      else
+        $cmd
+      fi
+    fi
   else
-    $cmd
+    echo -e $cyn"running $cmd$rst"
+    echo
+    if [[ $sdo == "y" ]] ; then
+      sudo $cmd
+    else
+      $cmd
+    fi
   fi
 }
 
@@ -170,6 +202,10 @@ shellcheck_setup() {
 }
 
 sudo -v # gets user password for next sudos
+
+if [ "$1" == "-y" ]; then
+  all="-y"
+fi
 
 cd "$HOME"
 announce PREREQUISITES
